# Generated by Django 4.0.1 on 2022-01-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
